service: community-chat-app

org: null
app: null

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1

functions:
  chatHandler:
    handler: backend/lambda_function.lambda_handler
    events:
      - http:
          path: chat
          method: post

package:
  patterns:
    - backend/**
    - '!node_modules/**'
    - '!**/*.test.*'
